// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.12.3
// source: podlifecycle.proto

package podlifecycle

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StuffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StuffRequest) Reset() {
	*x = StuffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podlifecycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StuffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuffRequest) ProtoMessage() {}

func (x *StuffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podlifecycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuffRequest.ProtoReflect.Descriptor instead.
func (*StuffRequest) Descriptor() ([]byte, []int) {
	return file_podlifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *StuffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StuffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StuffResponse) Reset() {
	*x = StuffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podlifecycle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StuffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuffResponse) ProtoMessage() {}

func (x *StuffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podlifecycle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuffResponse.ProtoReflect.Descriptor instead.
func (*StuffResponse) Descriptor() ([]byte, []int) {
	return file_podlifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *StuffResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_podlifecycle_proto protoreflect.FileDescriptor

var file_podlifecycle_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6f, 0x64, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x74, 0x75, 0x66,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x35, 0x0a,
	0x07, 0x53, 0x74, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x07, 0x44, 0x6f, 0x53, 0x74,
	0x75, 0x66, 0x66, 0x12, 0x0d, 0x2e, 0x53, 0x74, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x74, 0x75, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x70, 0x6f, 0x64, 0x6c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_podlifecycle_proto_rawDescOnce sync.Once
	file_podlifecycle_proto_rawDescData = file_podlifecycle_proto_rawDesc
)

func file_podlifecycle_proto_rawDescGZIP() []byte {
	file_podlifecycle_proto_rawDescOnce.Do(func() {
		file_podlifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_podlifecycle_proto_rawDescData)
	})
	return file_podlifecycle_proto_rawDescData
}

var file_podlifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podlifecycle_proto_goTypes = []interface{}{
	(*StuffRequest)(nil),  // 0: StuffRequest
	(*StuffResponse)(nil), // 1: StuffResponse
}
var file_podlifecycle_proto_depIdxs = []int32{
	0, // 0: Stuffer.DoStuff:input_type -> StuffRequest
	1, // 1: Stuffer.DoStuff:output_type -> StuffResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podlifecycle_proto_init() }
func file_podlifecycle_proto_init() {
	if File_podlifecycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_podlifecycle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StuffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podlifecycle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StuffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_podlifecycle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podlifecycle_proto_goTypes,
		DependencyIndexes: file_podlifecycle_proto_depIdxs,
		MessageInfos:      file_podlifecycle_proto_msgTypes,
	}.Build()
	File_podlifecycle_proto = out.File
	file_podlifecycle_proto_rawDesc = nil
	file_podlifecycle_proto_goTypes = nil
	file_podlifecycle_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StufferClient is the client API for Stuffer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StufferClient interface {
	DoStuff(ctx context.Context, in *StuffRequest, opts ...grpc.CallOption) (*StuffResponse, error)
}

type stufferClient struct {
	cc grpc.ClientConnInterface
}

func NewStufferClient(cc grpc.ClientConnInterface) StufferClient {
	return &stufferClient{cc}
}

func (c *stufferClient) DoStuff(ctx context.Context, in *StuffRequest, opts ...grpc.CallOption) (*StuffResponse, error) {
	out := new(StuffResponse)
	err := c.cc.Invoke(ctx, "/Stuffer/DoStuff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StufferServer is the server API for Stuffer service.
type StufferServer interface {
	DoStuff(context.Context, *StuffRequest) (*StuffResponse, error)
}

// UnimplementedStufferServer can be embedded to have forward compatible implementations.
type UnimplementedStufferServer struct {
}

func (*UnimplementedStufferServer) DoStuff(context.Context, *StuffRequest) (*StuffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoStuff not implemented")
}

func RegisterStufferServer(s *grpc.Server, srv StufferServer) {
	s.RegisterService(&_Stuffer_serviceDesc, srv)
}

func _Stuffer_DoStuff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StufferServer).DoStuff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stuffer/DoStuff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StufferServer).DoStuff(ctx, req.(*StuffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stuffer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Stuffer",
	HandlerType: (*StufferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoStuff",
			Handler:    _Stuffer_DoStuff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podlifecycle.proto",
}
